# Generated by Django 4.1.5 on 2023-01-22 23:56

import core.validations.validations_receiver
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField(verbose_name='Conta')),
                ('account_type', models.CharField(choices=[('C', 'Corrente'), ('P', 'Poupança')], max_length=1, verbose_name='Tipo de conta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=250, verbose_name='Nome do Banco')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['-bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=14, validators=[core.validations.validations_receiver.only_int], verbose_name='CPF/CNPJ')),
                ('status', models.CharField(choices=[('V', 'Validado'), ('R', 'Rascunho')], max_length=1, verbose_name='Status')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-mail')),
                ('key_type', models.CharField(choices=[('PHONE', 'Telefone'), ('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'Email'), ('ALKEY', 'Chave Aleatória')], max_length=5, verbose_name='Tipo de Chave Pix')),
                ('key', models.CharField(max_length=250, verbose_name='Chave Pix')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('account', models.ManyToManyField(blank=True, to='core.account')),
            ],
            options={
                'verbose_name': 'Recebedor',
                'verbose_name_plural': 'Recebedores',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_number', models.IntegerField(verbose_name='Agência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('from_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bank', verbose_name='Banco')),
            ],
            options={
                'verbose_name': 'Agência',
                'verbose_name_plural': 'Agência',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='from_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.agency', verbose_name='Agência'),
        ),
    ]
