# Generated by Django 4.1.5 on 2023-01-23 13:03

import core.validations.validations_receiver
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[core.validations.validations_receiver.only_int], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='key',
            field=models.CharField(max_length=250, unique=True, verbose_name='Chave Pix'),
        ),
    ]
