# Generated by Django 4.1.5 on 2023-01-23 13:06

import core.validations.validations_receiver
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_receiver_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, validators=[core.validations.validations_receiver.only_int], verbose_name='CPF/CNPJ'),
        ),
    ]
